[scheduler]
max_concurrent_experiments = 2
check_interval = 5
base_experiment_dir = "./experiments_long_demo"
auto_restart_on_error = true

[[experiments]]
name = "slow_baseline"
command = "python toy_example/slow_experiment.py --duration 150 --interval 15 --workload baseline"
priority = 50
cwd = "."
description = "150 秒基线任务，15 秒刷新一次日志"
max_retries = 2

delay_seconds = 0

[experiments.environment]
PYTHONUNBUFFERED = "1"

[[experiments]]
name = "slow_with_jitter"
command = "python toy_example/slow_experiment.py --duration 210 --interval 20 --jitter 5 --workload jitter"
priority = 30
cwd = "."
description = "210 秒任务，带随机扰动，用于观察运行时间波动"

delay_seconds = 10

[experiments.environment]
PYTHONUNBUFFERED = "1"

[[experiments]]
name = "slow_long_tail"
command = "python toy_example/slow_experiment.py --duration 270 --interval 30 --workload long_tail"
priority = 10
cwd = "."
description = "270 秒长尾任务，30 秒记录一次进度"

[experiments.environment]
PYTHONUNBUFFERED = "1"
